export const browserCoreExamples = [
  "sigil browser status",
  "sigil browser start",
  "sigil browser stop",
  "sigil browser tabs",
  "sigil browser open https://example.com",
  "sigil browser focus abcd1234",
  "sigil browser close abcd1234",
  "sigil browser screenshot",
  "sigil browser screenshot --full-page",
  "sigil browser screenshot --ref 12",
  "sigil browser snapshot",
  "sigil browser snapshot --format aria --limit 200",
  "sigil browser snapshot --efficient",
  "sigil browser snapshot --labels",
];

export const browserActionExamples = [
  "sigil browser navigate https://example.com",
  "sigil browser resize 1280 720",
  "sigil browser click 12 --double",
  'sigil browser type 23 "hello" --submit',
  "sigil browser press Enter",
  "sigil browser hover 44",
  "sigil browser drag 10 11",
  "sigil browser select 9 OptionA OptionB",
  "sigil browser upload /tmp/file.pdf",
  'sigil browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "sigil browser dialog --accept",
  'sigil browser wait --text "Done"',
  "sigil browser evaluate --fn '(el) => el.textContent' --ref 7",
  "sigil browser console --level error",
  "sigil browser pdf",
];
